### ISSUE TITLE
Set environment value in fabric.mod.json

### ISSUE THREAD

**Issue by calloatti** [juliand665/Dynamic-FPS#1]
I am guessing this is a client side mod, since it would be pointless in a dedicated server.

You should set the environment value in fabric.mod.json to "client" probably.

**Comment by juliand665** [comment]
Oh, I was wondering how I could specify that. Thanks!

**Comment by juliand665** [comment]
Does this make the mod not load on servers rather than crashing?

**Comment by calloatti** [comment]
It did not crash for me. But yes, a server will just ignore the mod, and also having environment set to  client enables modpack creation tools to just not copy the mod to a dedicated server instance.

https://fabricmc.net/wiki/documentation:fabric_mod_json
