### ISSUE TITLE
Conflict with rrls (RemoveReloadingScreen)

### ISSUE THREAD

**Issue by dima-dencep** [juliand665/Dynamic-FPS#100]
I don't think anything needs to be detailed, you can check everything yourself

![https://media.essential.gg/b2da7349-28f9-47c7-d3d3-040d88723100](https://imagedelivery.net/W9K_l6ndK9x4x8m3rurakg/b2da7349-28f9-47c7-d3d3-040d88723100/original)

I also think you know what the cause is, but if not, the problem is [here](https://github.com/juliand665/Dynamic-FPS/blob/main/src/main/java/dynamicfps/mixin/GameRendererMixin.java#L29-L40).

**Comment by LostLuma** [comment]
Hey, thanks for the report! I've implemented a fix for this locally that I will push later (have some other work in-progress first).
