### ISSUE TITLE
High GPU usage when game is in background

### ISSUE THREAD

**Issue by JustAlittleWolf** [juliand665/Dynamic-FPS#105]
When leaving fps uncapped in Dynamic FPS 3.0.0 the fps skyrockets from 200 to about 2000 (although world rendering is visibly rendered at a lower framerate) causing extremely high GPU usage. even more than when focused. 

https://i.imgur.com/Nk8GAf7.mp4

**Comment by JustAlittleWolf** [comment]
minecraft version: 1.20.1

mods used:
        - betterpingdisplay 1.1.1
	- blur 3.1.0
	   |-- midnightlib 1.4.1
	   \-- satin 1.13.0
	- bobby 5.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- borderlessmining 1.1.8+1.20.1
	- c2me 0.2.0+alpha.10.100
	   |-- c2me-base 0.2.0+alpha.10.100
	   |-- c2me-client-uncapvd 0.2.0+alpha.10.100
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.10.100
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.10.100
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.10.100
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.10.100
	   |-- c2me-notickvd 0.2.0+alpha.10.100
	   |-- c2me-opts-allocs 0.2.0+alpha.10.100
	   |-- c2me-opts-chunk-access 0.2.0+alpha.10.100
	   |-- c2me-opts-chunkio 0.2.0+alpha.10.100
	   |-- c2me-opts-math 0.2.0+alpha.10.100
	   |-- c2me-opts-scheduling 0.2.0+alpha.10.100
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.10.100
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.10.100
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.10.100
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.10.100
	   |-- c2me-server-utils 0.2.0+alpha.10.100
	   |-- c2me-threading-chunkio 0.2.0+alpha.10.100
	   |-- c2me-threading-lighting 0.2.0+alpha.10.100
	   |-- c2me-threading-worldgen 0.2.0+alpha.10.100
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- camerautils 1.20.1-1.0.5
	   \-- fabric-key-binding-api-v1 1.0.36+fb8d95da82
	- capes 1.5.2+1.20
	- carpet 1.4.112+v230608
	- chat_heads 0.10.20
	- chatpatches 201.5.5
	- continuity 3.0.0-beta.3+1.20.1
	- craterlib 1.0.2
	- dark-loading-screen 1.6.14
	- dynamic_fps 3.0.0
	- enhancedblockentities 0.9+1.20
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- entityculling 1.6.2-mc1.20
	- exit_confirm 2.5.0-mc.1.20.1
	- exordium 1.1.4-mc1.20.1
	- fabric-api 0.87.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
	   |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabrication 3.3.1+1.20
	   \-- lib39-deferral 1.5.0-pre2.2+1.19.3
	- fabricforcelowercase 2.1.0
	- fabricloader 0.14.22
	- faster_entity_animations 1.6
	- fastipping 1.0.0
	- ferritecore 6.0.0
	- fixelytrabug 1.1.0
	- forcecloseworldloadingscreen 2.1.1
	- ias 8.0.2
	- immediatelyfast 1.2.1+1.20.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.10
	   \-- net_lenni0451_reflect 1.2.1
	- indium 1.0.25+mc1.20.1
	- iris 1.6.8
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazy-language-loader 0.3.3
	- lithium 0.11.2
	- minecraft 1.20.1
	- modernfix 5.7.2+mc1.20.1
	- modify-camera-collision 1.0.0
	- modmenu 7.2.1
	- moreculling 1.20.1-0.19.0
	   \-- conditional-mixin 0.3.2
	- my-beloved-icon 1.0-SNAPSHOT
	- nbt_ac 1.1.6
	- nbttooltips 0.1.4-1.20.x
	- no-telemetry 1.7.0
	- no_fog 1.3.4+1.16.5-1.20.1
	- nochatreports 1.20.1-v2.2.2
	- norefreshscroll 1.0.5
	- playerfinder 1.0.2
	- playerspectator 1.2.1-hidden+1.20
	   \-- cloth-config 11.1.106
	        \-- cloth-basic-math 0.6.1
	- presencefootsteps 1.9.0
	   \-- kirin 1.15.0
	- rebind_narrator 2.0.2
	- serverpingerfixer 1.0.1
	- simple-rpc 3.2.2
	   \-- me_hypherionmc_simplerpc_simple-rpc-common 5.0.0
	- skinlayers 1.5.4-mc1.20.1
	- smoothscrollingeverywhere 3.0.6
	   \-- cloth-config 11.1.106
	        \-- cloth-basic-math 0.6.1
	- sneaktweak 1.9.1
	- sodium 0.5.2
	- soundcontroller 0.1.0
	- spark 1.10.42
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- starlight 1.1.2+fabric.dbc156f
	- threadtweak 1.20.1-0.1.0
	- timechanger 1.4.1
	- viafabric 0.4.10+409-main
	   |-- org_yaml_snakeyaml 2.0
	   |-- viafabric-mc120 0.4.10+409-main
	   \-- viaversion 4.7.1-SNAPSHOT
	- visiblebarriers 2.0.8
	- waveycapes 1.3.2
	- worldedit 7.2.15+6463-5ca4dff
	- yet_another_config_lib_v3 3.1.1+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6

**Comment by LostLuma** [comment]
Hello, thanks for the report. I've tested and this is an incompatibility with Dynamic FPS 3.x and Fabrication which we can pretty easily resolve it seems, I'll take a closer look at it tomorrow. For now you can use the older Dynamic FPS since it should still work 🦫
