### ISSUE TITLE
No way to uncap fps in menus

### ISSUE THREAD

**Issue by lucy** [juliand665/Dynamic-FPS#113]
There doesn't seem to be a way to make dynamic-fps not cap the frame rate to 60 on the pause menu while the game is focused. It also overrides <https://modrinth.com/mod/smoothmenu-refabricated> in the main menus other than the title screen. I'd like to use the higher cap I have set in video settings to make the mouse feel smooth on my VRR monitor.

**Comment by LostLuma** [comment]
Hello, thanks for the report. It seems this feature causes more of a headache than it should so I will see about making it opt-in and/or only apply it on the actual pause screen in the next release.
