### ISSUE TITLE
Failed to load config screen: NoSuchFieldError: field_22735

### ISSUE THREAD

**Issue by justdmitry** [juliand665/Dynamic-FPS#132]
Minecraft 1.20.1, Quilt, Dynamic FPS 3.2.1

ModMenu fails to show config screen, reports error:
![image](https://github.com/juliand665/Dynamic-FPS/assets/3540597/1a8e8c34-b86c-4782-abd6-b6a5492fd16f)

**Comment by LostLuma** [comment]
Hello, this is most likely an incompatibility with another mod, and not an issue with Dynamic FPS itself. Could you provide a full Minecraft log so we can look into this further?

**Comment by LostLuma** [comment]
Actually looking into it it seems like you've downloaded Dynamic FPS for an older Minecraft version, though I'm unsure how you go it to run on 1.20.1 (unless you used a dependency override, but then you should generally not expect things to work or ask for support).

The version I pushed to Modrinth / CurseForge yesterday is only for 1.16.5 to 1.18.2, and contains no other features over the other 3.2.1 versions. 
![image](https://github.com/juliand665/Dynamic-FPS/assets/38926001/33de15c5-3899-4276-9428-2aa8b1bc9b03)

**Comment by justdmitry** [comment]
> Actually looking into it it seems like you've downloaded Dynamic FPS for an older Minecraft version

No, I have `dynamic-fps-3.2.1+minecraft-1.20.0.jar` in mods folder.


> Could you provide a full Minecraft log so we can look into this further?

```
[Render thread/ERROR]: Error from mod 'dynamic_fps'
java.lang.NoSuchFieldError: field_22735
  at me.shedaniel.clothconfig2.impl.ConfigBuilderImpl.<init>(ConfigBuilderImpl.java:54) ~[transformed-mod-cloth-config.i0:0/:?]
  at me.shedaniel.clothconfig2.api.ConfigBuilder.create(ConfigBuilder.java:36) ~[transformed-mod-cloth-config.i0:0/:?]
  at dynamic_fps.impl.compat.ClothConfig.genConfigScreen(ClothConfig.java:16) ~[transformed-mod-dynamic-fps.i0:0/:?]
  at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:61) ~[transformed-mod-modmenu.i0:0/:?]. 
  ...
```


> incompatibility with another mod

Indeed. Found in log that I have other [old] plugin nbttooltip with embedded Cloth Config (v0.9). Installed latest Cloth Config (even without removing nbttooltip) and everything works now!

Thank you for help!

**Comment by LostLuma** [comment]
Guess that'd lead to the same error, glad you found it! :)
