### ISSUE TITLE
Make 60fps cap optional

### ISSUE THREAD

**Issue by Felix14-v2** [juliand665/Dynamic-FPS#133]
### Description
New DynamicFPS versions introduces new (and pretty inconvenient) feature which forcefully reduces FPS to 60 at certain screens. For example, pause menu or "soft" pause (F3+ESC).

### Pause menu
In this case we have a conflict with VulkanMod (flashing images!):

https://github.com/juliand665/Dynamic-FPS/assets/75726196/60dbe155-c9c6-46f1-8e0f-2c20e4ad648d

### Soft pause
Generally, this feature is used for the rendering performance benchmarking without performance loss on integrated server processing. So it doesn't make sense to reduce FPS on this screen.

## Additional
It would be great to make the 60 FPS limit configurable. For example, on my 144Hz screen 60 FPS isn't perceived very well.

**Comment by LostLuma** [comment]
At first glance this sounds pretty reasonable, however I'm curious whether this mod combination also causes flashing in other situations for you (when tabbed out while on the pause screen for example, maybe play around with different FPS targets)? If it does it is also worth reporting this to VulkanMod itself, as I don't think this is something we can actually properly fix on our side.

**Comment by Felix14-v2** [comment]
Personally, compatibility with VulkanMod does not really important for me, since VulkanMod itself contains similar optimizations. However, I have to delete DynamicFPS every time I benchmark my FPS, because the 60 FPS limit cannot be disabled.

**Comment by LostLuma** [comment]
The pause screen behavior has been removed entirely since it seems to have more downsides than upsides.  
Since I'm not entirely sure when I will release a new version yet (am busy), you might want to download it [from CI](https://github.com/juliand665/Dynamic-FPS/actions) instead.
