### ISSUE TITLE
Doesn't work on amd

### ISSUE THREAD

**Issue by aboba1336** [juliand665/Dynamic-FPS#138]
Fabric 1.20.2. Doesn't work on amd ryzen/radeon. I have a laptop with an Intel, everything works fine there. I have attached a file with an Issue. Sorry for the bad English, used Google Translate
[issue.txt](https://github.com/juliand665/Dynamic-FPS/files/13531501/issue.txt)

**Comment by LostLuma** [comment]
Hello, this is does not seem to be an issue with a particular CPU or GPU vendor, but rather that your config file seems to have been corrupted. You should be able to go to your `.minecraft/config` directory and simply delete `dynamic_fps.json` to make it work.

**Comment by aboba1336** [comment]
Thank you very much, it worked!
