### ISSUE TITLE
3.3.0 resets volume to maximum after alt-tab

### ISSUE THREAD

**Issue by treacherousfiend** [juliand665/Dynamic-FPS#144]
In the latest version of the mod, alt-tabbing out and back in will cause the in-game volume to reset to 100%, regardless of what your Minecraft audio settings are.
Just to clarify, this is NOT an issue with the mod's volume multiplier itself, but rather the mod not reverting back to Minecraft's built-in volume settings when alt-tabbing back in, and instead just setting it to 100%.

Dynamic FPS 3.3.0
Minecraft 1.20.4
Quilt Launcher 0.22.1-beta.4

Example:
1. Set Minecraft Master volume to 30%
2. Alt-tab out and back in
3. Sounds played after doing this will be played at 100% volume rather than 30%
This issue can be worked around by going back into Minecraft's options menu and updating the volume settings.

Video showcasing the bug:
Volume set to 0% to better show off the issue, the slight freeze around 3 seconds in is my alt-tabbing in and out
[MinecraftDynamicFpsSoundBug.webm](https://github.com/juliand665/Dynamic-FPS/assets/46549454/5d93ced0-5271-4e99-b831-8f4a3303963e)

**Comment by LostLuma** [comment]
Annoying. Sadly I didn't spot this because I had master volume at 100% during testing, but it's pretty easy to fix it seems.
