### ISSUE TITLE
Some audio levels are not matching the vanilla game

### ISSUE THREAD

**Issue by aerulion** [juliand665/Dynamic-FPS#153]
Since updating the mod, I noticed that some audio levels do not match the vanilla game anymore.
With my current setup, I always have the master volume set to 3%, while any other category is set to 100%. When using this mod, I can barely hear the UI sound of the game (button clicks, ...), while I can hear them normally without the mod.

**Comment by andreasdc** [comment]
I have the same issue, but I didn't think it is caused by this mod.
