### ISSUE TITLE
Volume reducer not working as intended

### ISSUE THREAD

**Issue by N1zle** [juliand665/Dynamic-FPS#157]
I currently have this mod enabled, with Master volume at 15%, Music at 10%, blocks at 20% etc. Whenever I alt tab and the mod kicks in, it reduces my fps as it should, and reduces that volume even lower by the multiplier set in the ModMenu > DynamicFPS settings. However, when I click back in the game, it just blasts my volume all the way back to 100%.

It doesn't change my in game settings, the sliders don't move. All I need to do is go back in the Music & Sound tab and click Done and it goes back to my usual settings. But I shouldn't need to do that, the mod should remove the multiplier and go back to my set volume, not 100%,

**Comment by LostLuma** [comment]
You're running and outdated version of the mod, this was fixed in version 3.3.1.

Also:

> and reduces that volume even lower by the multiplier set in the ModMenu > DynamicFPS settings

The volume multiplier is called a multiplier and not just "volume" because it multiplies your current volume by this value. If you have music set to 50% and apply a 50% multiplier to music you will end up with 25% volume while tabbed out.

**Comment by N1zle** [comment]
Thanks for the reply!

Yes I am indeed running an outdated version, as I haven't touched Minecraft at all for a while and forgot how to work my way around PrismLauncher. I updated it to 3.3.3, but the required Fabric launcher 15.6 broke the rest of my modpack. Manually selected 3.3.1 now, works wonders.

> and reduces that volume even lower by the multiplier set in the ModMenu > DynamicFPS settings

And yes, I understand the multiplier thing. Sorry if I was not clear, I just wanted to describe that the multiplier was working as intended. English is not my first language, maybe I could have worded it better.

**Comment by LostLuma** [comment]
No worries!
