### ISSUE TITLE
Sudden incompatibility issue with Dynamic Surroundings as of the latest build of the mod on 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [juliand665/Dynamic-FPS#168]
https://pastebin.com/BXAYKN0s

This crash report seems misleading at first, but when turning off your mod, I am able to boot up fine.

**Comment by LostLuma** [comment]
Unfortunate. This is due to me working around an issue in our build tooling (see description of #164).  
I can definitely fix this in a few hours (have to sleep soon!) but it'll be a bit more effort on my part to release.

**Comment by LostLuma** [comment]
Hi, this should be resolved in version 3.4.1. It's available on GitHub now and will be elsewhere in a bit.
