### ISSUE TITLE
compatibility issue with fast load mod

### ISSUE THREAD

**Issue by papamaionise** [juliand665/Dynamic-FPS#173]
![Screenshot (1323)](https://github.com/juliand665/Dynamic-FPS/assets/126779287/1fc1bcf3-0c43-44f3-8cea-575426cb1795)

fastload used to work with previous version of dynamic fps

**Comment by LostLuma** [comment]
See #169. This will be resolved in the next update.

**Comment by papamaionise** [comment]
> See #169. This will be resolved in the next update.

oh ok thanks
