### ISSUE TITLE
Neoforge dynamic-fps crashed my neoforge instance, but the forge one works fine with neoforge loader

### ISSUE THREAD

**Issue by liangmoe** [juliand665/Dynamic-FPS#174]
crash report: https://mclo.gs/bOElSGs
latest: https://mclo.gs/blIbAvu
debug: https://mclo.gs/K5x12WO

the working latest(forge dynamicfps with neoforge instance): https://mclo.gs/mpmkdE3

**Comment by LostLuma** [comment]
Hello, thanks for the heads up! The NeoForge version of the mod should've only been marked as compatible with Minecraft 1.20.2 to 1.20.4 on Modrinth, not 1.20.1. To play with Dynamic FPS on Minecraft 1.20.1 with NeoForge you'll want to download the regular Forge version, as it is compatible with NeoForge on that version.

**Comment by liangmoe** [comment]
alr, thanks!
