### ISSUE TITLE
V3.4.2 on 1.20.4 Requires QSL (which doesn't exist)

### ISSUE THREAD

**Issue by LizzieSpace** [juliand665/Dynamic-FPS#175]
The mod version [3.4.2](https://github.com/juliand665/Dynamic-FPS/releases/tag/3.4.2) crashes minecraft 1.20.4 with the following message:
```
---- Quilt Loader: Failed to load ----
Date/Time: 2024/02/25 21:11:48.3927
Quilt Loader Version: 0.23.1
-- Error 1 --
Dynamic FPS requires any version of quilt_resource_loader, which is missing!
- <mods>/dynamic-fps-3.4.2+minecraft-1.20.4-quilt.jar
-- Error 2 --
Dynamic FPS requires any version of quilt_lifecycle_events, which is missing!
- <mods>/dynamic-fps-3.4.2+minecraft-1.20.4-quilt.jar
-- Plugin State --
Cycle number = 1
Cycle Step = SOLVE
Loaded Plugins (2):
 - 'quilt_loader' (Builtin)
 - 'quilted_fabric_loader' (Builtin)
---- end of report ----
```

The crash logs only report the aforementioned dependencies. No other useful information could be retrieved.

```
<mods>/dynamic-fps-3.4.2+minecraft-1.20.4-quilt.jar:
#################################################
#  Loaded by  'quilt_loader'                    #
#  Name     = 'Dynamic FPS'                     #
#  ID       = 'dynamic_fps'                     #
#  Version  = '3.4.2'                           #
#  LoadType = IF_REQUIRED                       #
#  Depends on 'quilt_loader' [0.23.1, ∞)        #
#  Depends on 'minecraft' [1.20.0, ∞)           #
#  Depends on 'mixinextras' [0.3.2, ∞)          #
#  Depends on 'quilt_resource_loader' (-∞, ∞)   #
#  Depends on 'quilt_lifecycle_events' (-∞, ∞)  #
#  Depends on 'modmenu' (-∞, ∞)                 #
#  Depends on 'cloth-config' (-∞, ∞)            #
#################################################
```
The issue most likely comes from the fact that the mod requires `quilt_resource_loader` and `quilt_lifecycle_events`. Both are a part of [QSL](https://github.com/QuiltMC/quilt-standard-libraries), which up until `Sunday, February 25, 2024` does not exist.

there is a pull request with a possible 1.20.4 update, but it has yet to be merged:
https://github.com/QuiltMC/quilt-standard-libraries/pull/356

**Comment by LostLuma** [comment]
Hello, you're indeed right that QSL for 1.20.4 is not out yet, however I've confirmed that once it is it will work properly with this version of Dynamic FPS.  
I assume you're running Quilt Loader and regular Fabric API on 1.20.4 while this is the case, if you'd like also to use Dynamic FPS you can use the Fabric version for now.

**Comment by Delivator** [comment]
What? How can this happen that a version is release for a modloader version that doesn't exist yet?

**Comment by LostLuma** [comment]
First of all, Quilt Loader is not version dependent, however the as original author linked above a QSL version for 1.20.4 is in the works and it does not contain any breaking changes for the modules that we use.
