### ISSUE TITLE
Snapshots support

### ISSUE THREAD

**Issue by TheBossMagnus** [juliand665/Dynamic-FPS#176]
Currently, DynamicFps is broken sync 24w09a. Is it possible to have a new version for it at least on Github action?

**Comment by LostLuma** [comment]
Hi, it is possible and I had some time so I've updated the mod to 14w09a and uploaded it to all three distribution platforms.  
Unsure whether I will keep this up with new snapshots as they come out if it breaks again, or just do the 1.20.5 update later.

**Comment by TheBossMagnus** [comment]
Ty, generally Dynamic Fps isn't too much breakage-prone with snapshots. If it breaks again I'll let you know!

**Comment by TheBossMagnus** [comment]
@LostLuma has broken again since 24w20a. Up to you to fix it or wait stable.....

**Comment by LostLuma** [comment]
I already released a new version a minute ago: https://modrinth.com/mod/dynamic-fps/version/OpDYYPhR
