### ISSUE TITLE
Dynamic FPS 3.4.2 问题

### ISSUE THREAD

**Issue by EndesrDragons** [juliand665/Dynamic-FPS#177]
最新版本3.4.2fabric端在1.20.4启动之后显示需要quilt_loader，但quilt和fabric不兼容，啥原因？

**Comment by LostLuma** [comment]
Hi, Quilt Loader is not required for running the Fabric version of the mod, but rather recommended (suggested may be a better word for translation?). If it was required the game would not launch.
