### ISSUE TITLE
New versions for snapshots not work because there is no mod "Cloth Config" for 1.20.5-pre1

### ISSUE THREAD

**Issue by PufferBluh** [juliand665/Dynamic-FPS#183]
The mod simply requires a mod Cloth Config, and the version of this mod is only for 1.20.4 and lower, of course, someone may say that this is not a Dynamic FPS problem, but then the question is: why was this mod for 1.20.5-pre1?

**Comment by LostLuma** [comment]
Cloth Config is an optional requirement that allows using the in game config screen, Dynamic FPS can be used without it.
If you'd like to use non-stock settings you can either edit the config file or copy one from a version where Cloth Config is available.

**Comment by PufferBluh** [comment]
> Cloth Config is an optional requirement that allows using the in game config screen, Dynamic FPS can be used without it. If you'd like to use non-stock settings you can either edit the config file or copy one from a version where Cloth Config is available.

Ok, I already understood, everything worked, it’s just that earlier for some reason the mod didn’t work for me, but as soon as I wrote about it, the mod started working for me.. um.. most likely it’s because of my stupidity because I’m probably doing something again got it mixed up

**Comment by LostLuma** [comment]
I see, no worries.
