### ISSUE TITLE
Mod requires Quilt Loader in Fabric instance

### ISSUE THREAD

**Issue by GhostOps77** [juliand665/Dynamic-FPS#185]
I tried to load in this mod in a fabric instance, and it displayed this message
```
 - Mod 'Dynamic FPS' (dynamic_fps) 3.4.3 recommends any version of quilt_loader, which is missing!
	 - You should install any version of quilt_loader for the optimal experience.
```
in that case, how do i even use this mod for its "optimal experience"?

but other than that, i can just run minecraft with this mod without any issues

**Comment by LostLuma** [comment]
You don't need to do anything, I just like the Quilt project so I put it as a "recommended" mod.
Maybe I'll remove this again in the future though since it seems to cause more confusion than anything ..

**Comment by GhostOps77** [comment]
alright, no issue then
closing the issue
