### ISSUE TITLE
[Suggestion] Add FPS display

### ISSUE THREAD

**Issue by HexedHero** [juliand665/Dynamic-FPS#19]
Display FPS in the top left corner. Could also make it red when the fps is limited from the mod.

**Comment by juliand665** [comment]
This is the most useless feature I felt FPS Reducer had, lol. I don't see what you gain from seeing a message that your fps is being reduced if your game is unfocused or hidden anyway? The only time we display text on-screen is when the reduction is temporarily disabled or forced even when active.

**Comment by dukebennson** [comment]
how do i display fps??

**Comment by dukebennson** [comment]
i downloaded this thing and it doesnt show the fps on the top left corner and the configure wont do anything do I need help.

**Comment by soahmkadam98-stack** [comment]
Good
