### ISSUE TITLE
Crash on 1.21

### ISSUE THREAD

**Issue by Avakining** [juliand665/Dynamic-FPS#192]
Dyanamic-FPS version: 3.4.3 (claims to have 1.21 support)
Fabric version: 0.15.11

[Full log](https://mclo.gs/loDRvx4)

[Just the crash report](https://mclo.gs/ItRRAgj)

**Comment by LostLuma** [comment]
You're running Dynamic FPS for 1.20.5 / 1.20.6, not 1.21.0.

**Comment by LostLuma** [comment]
If you downloaded from Modrinth you'll need to find it in the versions tab rather than on the left-hand side, for some reason 1.21 is not auto featured: https://modrinth.com/mod/dynamic-fps/version/jeq5Pk2P
