### ISSUE TITLE
Volume multiplier settings not loaded on startup

### ISSUE THREAD

**Issue by JasonHorkles** [juliand665/Dynamic-FPS#199]
When starting Minecraft, the mod reverts the master volume to the default value (at least for unfocused/invisible). The config shows the correct values though.
v3.5.0-beta.1 MC 1.21

**Comment by LostLuma** [comment]
Interesting! I can reproduce this when setting the master volume for the unfocused state to 100%, but not to any other value, is that also the case for you or does it happen for any percentage?

**Comment by LostLuma** [comment]
Well I think I've fixed the issue you've experienced, if I misunderstood please let me know.

**Comment by JasonHorkles** [comment]
I hadn't tested on other volumes and just the master volume. I'll give this a shot and see! Thanks!!

**Comment by JasonHorkles** [comment]
Seems to be working!

**Comment by LostLuma** [comment]
Awesome :)
