### ISSUE TITLE
No config being generated

### ISSUE THREAD

**Issue by MelanX** [juliand665/Dynamic-FPS#202]
Forge: 47.2.0
Dynamic FPS: 3.5.0
MC: 1.20.1

No config was generated. Didn't install cloth config. When trying to edit config ingame, it says I should install cloth config, or edit the config file. As the issue says, the config file can't be edited :(

The log said this:
```
[25Juni2024 16:14:56.615] [modloading-worker-0/WARN] [dynamic_fps/]: Dynamic FPS config corrupted! Starting with defaults ...
[25Juni2024 16:14:56.631] [modloading-worker-0/INFO] [dynamic_fps/]: Dynamic FPS 3.5.0 active on Forge!
```

**Comment by LostLuma** [comment]
Hi, if you'd like to edit the config you should probably still install Cloth Config as usual.

The reason that it's now optional to install alongside Dynamic FPS is so modpack creators don't have to include it in their modpacks if they do not want to (quite a few Fabric / Quilt modpacks do this). Maybe I should've worded the message a bit better :)

That being said, maybe having a little document with possible values for the config file is be interesting.  
The closest we have to that is the [default config file](https://github.com/juliand665/Dynamic-FPS/blob/main/platforms/common/src/main/resources/assets/dynamic_fps/data/default_config.json), but it doesn't tell you much about possible enum values.

**Comment by LostLuma** [comment]
The next release (`v3.6.1`) will now generate an empty config file and no longer log that warning on every startup.  
Other points I made regarding Cloth Config still being recommended to install still apply (and that won't change), I'll close this.
