### ISSUE TITLE
Crash on any config save

### ISSUE THREAD

**Issue by TechnoSparks** [juliand665/Dynamic-FPS#204]
### Brief environment information
Minecraft **1.20.1**
Fabric 0.15.11
Dynamic-FPS 3.5.0

Mods:
- Mod Menu [7.2.2]
- Fabric API [0.92.2+1.20.1]
- Cloth Config v11 [11.1.118]
- Dynamic FPS [3.5.0]

### Logs
Crash report: https://mclo.gs/o5q64k5
Client log: https://mclo.gs/q3zhK7k

### Steps to reproduce
- Create a new instance with above mods
- Go to mod list
- Open config for dynamic FPS
- Change something
- Save
- _Crash_

### My other attempts
- Downgrade Dynamic-FPS to 3.4.3 to generate config. Then upgrading back to latest version. Changing config still crashes the game

### My workaround at the moment
- Downgrade to version 3.4.3

**Comment by Firebolt360** [comment]
I also have experienced this issue. Can't figure out a workaround aside from downgrading to a previous version.

**Comment by LostLuma** [comment]
Thanks for the report! This is a pretty simple fix, I will release a small update shortly :)

**Comment by TechnoSparks** [comment]
Thank you for maintaining this very useful mod! 😄
