### ISSUE TITLE
Warning with new battery feature

### ISSUE THREAD

**Issue by MeeniMc** [juliand665/Dynamic-FPS#206]
`[10:05:52] [Render thread/ERROR] (ModNioResourcePack) Invalid path in mod resource-pack dynamic_fps: dynamic_fps:textures/battery/LICENSE, ignoring`

This has no gameplay effect of course, but simply putting the file somewhere else would silence the warning.

**Comment by LostLuma** [comment]
I assume just renaming it to `license` or `license.txt` might fix that.
Could you tell me what Minecraft version and mod loader you use since this doesn't seem to happen on 1.21.0 with Fabric?

**Comment by MeeniMc** [comment]
I am using the Prism launcher that may set verbosity of logging higher. 

MC 1.21, Fabric 0.15.11

**Comment by LostLuma** [comment]
Well I still can't get this to happen sadly. Could you try this build and see if it fixes it:

https://github.com/LostLuma/Dynamic-FPS/actions/runs/9854586279
From the Artifacts section, download `dynamic-fps-artifacts`, open it, the mod is in the `platforms/fabric/build/libs` folder.

**Comment by MeeniMc** [comment]
The artifact looks like its not complaining

**Comment by LostLuma** [comment]
Awesome! I will include that in the next release then :)
