### ISSUE TITLE
[Bug]  Compatibility with 1.16.5 incorrectly set for version 1.16.4 on CurseForge

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [juliand665/Dynamic-FPS#207]
https://www.curseforge.com/minecraft/mc-mods/dynamic-fps/files/all?page=1&pageSize=20&version=1.16.5&sortBy=name&sortOrder=asc

Contains mods that only work with version 1.16.4

**Comment by LostLuma** [comment]
Which of these don't work on 1.16.5?

**Comment by wuliaodexiaoluo** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4163#issuecomment-2211602179

Sorry for the trouble. I forgot to test this issue. It is indeed supported, but I didn't understand it because the error message was in English, and I saw 1.16.4 in the file name, so I thought it was a platform label issue.

**Comment by LostLuma** [comment]
No worries :) I already guessed that it'd just be a little misunderstanding.
