### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by MechWheels** [juliand665/Dynamic-FPS#21]
Running 21w17a, ```
Could not find required mod: dynamicfps requires {fabric @ [*]}
Creating Empty clause ?
``` on launch. Running `dynamic-fps-2.0.1.jar` downloaded from Curseforge and running on `fabric-loader-0.11.3-21w17a`

![image](https://user-images.githubusercontent.com/11204286/116725487-cded4680-a996-11eb-9bba-47f2b79aa6fe.png)

**Comment by juliand665** [comment]
Are you maybe missing [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)?

**Comment by MechWheels** [comment]
Shoot sorry, that was the issue!
