### ISSUE TITLE
Not start 3.6.2 Quilt

### ISSUE THREAD

**Issue by mihalera** [juliand665/Dynamic-FPS#211]
1.21 Quilt loader 0.26.4 beta-1
DynamicFPS 3.6.2 for Quilt
QFAPI 11.0.0-alpha.3 and QSL 10.0.0-alpha.1
![Знімок екрана 2024-07-23 204554](https://github.com/user-attachments/assets/fd788d23-e93e-4a57-82ec-9e7483630f2c)
[crash-2024-07-23_20.40.05.4821-quilt_loader.txt](https://github.com/user-attachments/files/16352513/crash-2024-07-23_20.40.05.4821-quilt_loader.txt)

**Comment by TheBossMagnus** [comment]
can confirm, only happens on 1.21

**Comment by LostLuma** [comment]
Hi, this is the same situation as #175.
Once those QSL modules are released it'll work, until then you may want to install the Fabric version.

**Comment by TheBossMagnus** [comment]
Shouldn't the quilt version be unlisted or removed from modrinth?

**Comment by LostLuma** [comment]
I suppose unlisting it until the time is right might be a better user experience.

**Comment by TheBossMagnus** [comment]
> I suppose unlisting it until the time is right might be a better user experience.

i think you've unlisted only 3.6.2 and not 3.6.1

**Comment by LostLuma** [comment]
I was confused because setting the version as unlisted via the API made it disappear entirely seemingly, so I published it again and won't touch it anymore for now.
Next Minecraft release when QSL hangs behind a bit again I will just properly wait until the modules we need are out I think and then publish the Quilt version :)

**Comment by TheBossMagnus** [comment]
> I was confused because setting the version as unlisted via the API made it disappear entirely seemingly, so I published it again and won't touch it anymore for now. Next Minecraft release when QSL hangs behind a bit again I will just properly wait until the modules we need are out I think and then publish the Quilt version :)

You can't see it from the UI because archiving support isn't yet done. But it's still there on the api and you can unarchive through it

**Comment by LostLuma** [comment]
Quite weird, but I see, thanks. I think I will still just keep it listed and publish it at a better point in time in the future.

**Comment by LostLuma** [comment]
This is no longer an issue as of version 3.6.3.
