### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by andreasdc** [juliand665/Dynamic-FPS#212]
Sound is fading out even when I have unfocused sound on 100%.

**Comment by LostLuma** [comment]
Hello, I can not reproduce this issue. Could you upload your config file to see if that'd help diagnose the issue?

**Comment by andreasdc** [comment]
`{
  "idle": {
    "timeout": 60,
    "condition": "none"
  },
  "states": {
    "unfocused": {
      "frame_rate_target": 0,
      "volume_multipliers": {
        "master": 1.0
      },
      "graphics_state": "reduced",
      "run_garbage_collector": true
    },
    "abandoned": {
      "graphics_state": "reduced",
      "run_garbage_collector": true
    }
  }
}
`

**Comment by LostLuma** [comment]
Well that also did not help. Are you sure that the volume is actually changing (and not just cutting out for a brief moment when you tab out)? Or are you minimizing the window because then you'd need to configure the `Invisible` state to have no volume.

**Comment by andreasdc** [comment]
> Well that also did not help. Are you sure that the volume is actually changing (and not just cutting out for a brief moment when you tab out)? Or are you minimizing the window because then you'd need to configure the `Invisible` state to have no volume.

I was minimizing yes, now it works.

**Comment by LostLuma** [comment]
That's good to hear!
