### ISSUE TITLE
Options are not restored when improperly quitting the game

### ISSUE THREAD

**Issue by andreasdc** [juliand665/Dynamic-FPS#213]
I suppose the plugin changes the particles to minimal, but sometimes it doesn't revert it to decreased for example.

**Comment by LostLuma** [comment]
Hi, you need to provide more information if you'd like to receive help with this issue.
Please post your config file and also the exact steps you've taken to experience something you consider wrong.

**Comment by andreasdc** [comment]
> Hi, you need to provide more information if you'd like to receive help with this issue. Please post your config file and also the exact steps you've taken to experience something you consider wrong.
Don't know, I maximize minecraft and sometimes my settings are wrong.
```
{
  "idle": {
    "timeout": 60,
    "condition": "none"
  },
  "states": {
    "unfocused": {
      "frame_rate_target": 0,
      "volume_multipliers": {
        "master": 1.0
      },
      "graphics_state": "reduced",
      "run_garbage_collector": true
    },
    "abandoned": {
      "graphics_state": "reduced",
      "run_garbage_collector": true
    },
    "invisible": {
      "volume_multipliers": {
        "master": 0.7
      },
      "graphics_state": "reduced",
      "run_garbage_collector": true
    },
    "hovered": {
      "graphics_state": "reduced"
    }
  }
}
```

**Comment by LostLuma** [comment]
Does maximize mean entering actual fullscreen or having it use the full available space windowed?
And if it is fullscreen, are you using some sort of other mod to have borderless fullscreen or something similar?

**Comment by andreasdc** [comment]
> Does maximize mean entering actual fullscreen or having it use the full available space windowed? And if it is fullscreen, are you using some sort of other mod to have borderless fullscreen or something similar?

I mean alt tabbing, I don't have any other mod for fullscreen.

**Comment by LostLuma** [comment]
I see. Well I can not reproduce this issue so I am unsure how to help you at this time.

**Comment by andreasdc** [comment]
Well I had this setting changed 2 times, so it doesn't happen every time. Maybe something with switching quickly between states.

**Comment by LostLuma** [comment]
What do you mean you had this setting changed 2 times?

**Comment by andreasdc** [comment]
I noticed this bug 2 or 3 times.

**Comment by LostLuma** [comment]
Hmm. Well if you notice it again please let us know what exactly lead to it I suppose.

**Comment by andreasdc** [comment]
When I alt tab back it happens.

**Comment by andreasdc** [comment]
Issue still active

**Comment by LostLuma** [comment]
That's why it's still open, yes. Do you have any other info that would help me reproduce it, else it's pretty difficult to diagnose what is actually wrong. Maybe record a video of it happening or something?

**Comment by andreasdc** [comment]
When you start minecraft while minimized, it appears as decreased. When you have it on fullscreen it is normal.

**Comment by LostLuma** [comment]
How do I start Minecraft minimized?

**Comment by andreasdc** [comment]
Start minecraft and click on the other window when it's starting

**Comment by LostLuma** [comment]
Alright, I will try it out tomorrow since it's pretty late.

**Comment by LostLuma** [comment]
I still can not get this to work. Could you please record a video showing the process?

**Comment by andreasdc** [comment]
Video of launching the game when minimizing? When I start Minecraft I immediately want to alt tab to have the game minimized, it loads fully already minimized.

**Comment by LostLuma** [comment]
Yes. Record your desktop from the point you click launch in your launcher until you're in game and can show that the graphics settings are wrong.

**Comment by andreasdc** [comment]
I don't think I can do that unfortunately, but I just alt tab when the game is not loaded yet and it happens.

**Comment by juliand665** [comment]
[OBS](https://obsproject.com/) is a free software that can easily record your entire screen, if that's the issue here.

**Comment by andreasdc** [comment]
Will take a look at the recording for sure, how can I help more?

**Comment by LostLuma** [comment]
Just that would be good for now. The exact steps (and timings?) in a video should help a lot.  
If it's too big to upload here you might be able to create an unlisted YouTube video instead.

**Comment by andreasdc** [comment]
I can't record it, I just click anywhere on the screen to avoid loading it on fullscreen and it happens.

**Comment by juliand665** [comment]
Why can't you record it? What happens when you try?

**Comment by andreasdc** [comment]
I have too many files on my desktop, but these steps are really simple.

**Comment by juliand665** [comment]
If that's the only problem, you're in luck! https://support.microsoft.com/en-us/windows/show-hide-or-resize-desktop-icons-2b9334e6-f8dc-7098-094f-7e681a87dd97

**Comment by andreasdc** [comment]
I really don't feel comfortable doing that, but I can help in any other way.

**Comment by LostLuma** [comment]
Well then I doubt we can really do anything about this. I've tried launching the game and clicking or tabbing out at different points during loading tens of times and never gotten this issue. Without further info from you there's no way to resolve this on our side.

**Comment by andreasdc** [comment]
Well, that's what happens. Can we implement some kind of fix?

**Comment by LostLuma** [comment]
How do you propose we implement a fix if we do not know what the issue is?

**Comment by andreasdc** [comment]
Graphics are not being saved after the game has changed graphics to minimal? Then it can't be restored to the original value?

**Comment by LostLuma** [comment]
I'm not sure I understand what you just wrote. Anyway, two things I forgot to ask:
- What operating system and version do you use? And if you're on Linux, do you run Wayland or X?
- Can you reproduce this if you only have Fabric API and Dynamic FPS (with absolutely no other mods)?

**Comment by andreasdc** [comment]
> I'm not sure I understand what you just wrote. Anyway, two things I forgot to ask:
> 
> * What operating system and version do you use? And if you're on Linux, do you run Wayland or X?
> * Can you reproduce this if you only have Fabric API and Dynamic FPS (with absolutely no other mods)?

I use windows 11 dynamic-fps-3.6.1+minecraft-1.20.0-fabric
I will try to do it only with this mod, maybe it's with rrls, loading-window-1.0.0 or something.

**Comment by LostLuma** [comment]
>  I will try to do it only with this mod, maybe it's with rrls, loading-window-1.0.0 or something.

So what's the result of this?

**Comment by andreasdc** [comment]
Result is that probably DynamicFPS changes the graphics when you disable the Minecraft.

**Comment by LostLuma** [comment]
What?

**Comment by andreasdc** [comment]
> What?

After disabling Minecraft my graphics are already reverted.

**Comment by LostLuma** [comment]
What do you mean by disabling Minecraft?

**Comment by andreasdc** [comment]
> What do you mean by disabling Minecraft?

Closing it by "Quit game" button? 👁️ 😕

**Comment by LostLuma** [comment]
I see. The mod does not change the graphics (or do anything at all) when you quit the game, so that theory is wrong.

**Comment by andreasdc** [comment]
> I see. The mod does not change the graphics (or do anything at all) when you quit the game, so that theory is wrong.

It changes when you minimize, when you close when minimized I guess the graphics are from the minimized state.

**Comment by LostLuma** [comment]
... and that would be a completely different bug report and actually makes sense.

**Comment by andreasdc** [comment]
> ... and that would be a completely different bug report and actually makes sense.

Well this report is describing the issue, but I'm happy that I helped. 😺

**Comment by andreasdc** [comment]
> Hello, after quite a lot of debating on how to go about fixing this I have a build for you to test: [dynamic-fps-3.7.2-alpha.1+minecraft-1.21.2-alpha.24w33a-fabric.jar](https://files.lostluma.net/dynamic-fps-3.7.2-alpha.1+minecraft-1.21.2-alpha.24w33a-fabric.jar)
> 
> You will need to run it in any 1.21.2 snapshot equal to or newer than `24w33a`. I don't think other mods such as Cloth Config are available for the snapshots yet, so you'll want to copy the config file from your regular Minecraft instance to your snapshot instance for testing.
> 
> Please let me know whether this fixes the issue by testing a few times.

I would save the changed settings and check if the state is still for minimized setttings, if yes i would just revert it. I don't have 1.21.2 yet, but when I'll have I will test it. :)

**Comment by LostLuma** [comment]
I've already done such testing. The reason I asked for you to personally do it is because you've historically not been very great at describing what any specific issue actually is, and I wanted to confirm that this is actually the bug you were reporting originally.
