### ISSUE TITLE
its over

### ISSUE THREAD

**Issue by SergioK29** [juliand665/Dynamic-FPS#214]
What do you think about mojang adding dynamic fps in vanilla in latest snapshot? https://youtu.be/JfkfP-i3w3Y?t=1034

**Comment by juliand665** [comment]
It's cool to see this QoL feature finally coming to vanilla! Dynamic FPS still does more (volume, power states, hover) and is a ton more configurable, but our market is definitely about to shrink by a lot.

**Comment by megabyte6** [comment]
@juliand665 Thanks for developing Dynamic FPS for the last 5 years! I'm so happy Mojang is finally implementing these QoL features into the base game. When 1.21.2 releases, I'll likely opt for the vanilla implementation even though Dynamic FPS offers more features. From what I've seen, the vanilla option offers what I need. I definitely won't be forgetting this mod!

**Comment by LostLuma** [comment]
I'll see if I can experiment with that soon, but I'm still not 100% convinced it'll actually be nice to play with in practice.  
For now I have released [`v3.7.0`](https://github.com/juliand665/Dynamic-FPS/releases/tag/3.7.0) which allows Dynamic FPS and the new vanilla features to live alongside each other.
