### ISSUE TITLE
Flickering/jittering with Vulkanmod

### ISSUE THREAD

**Issue by AlexanderwithaA** [juliand665/Dynamic-FPS#227]
When Vulkanmod and DynamicFPS are used together you get some terrible sort of flickering/jittering. It'd appear to be between new and old frames and effects all parts of the game. Being unnfocused but hovered over and being unfocused causes this issue.

https://github.com/user-attachments/assets/0ae00342-110e-4e31-83b4-b373183d1f1d

**Comment by LostLuma** [comment]
You'll want to report this to VulkanMod (if it hasn't already been).
If you still want to use the two together you can set the FPS limit while unfocused to 15, it lessens the effect quite a bit.
