### ISSUE TITLE
Why dynamic FPS will eat somany performance

### ISSUE THREAD

**Issue by Blalala6868** [juliand665/Dynamic-FPS#229]
https://spark.lucko.me/1fdAZd0c3a
![image](https://github.com/user-attachments/assets/c7025740-3922-45a6-86fd-356a850b0c9f)

**Comment by LostLuma** [comment]
I'm not sure why Spark is attributing this to Dynamic FPS, no mod method calls are even found in the call chain ...

It's normal vanilla behavior for the server to run a tick and then have the thread sleep a bit less than a 20th of a second until the next tick to perform more work. All the `LockSupport.parkNanos()` method does is park (make the thread sleep / wait) the amount of nanoseconds the called asks for.
