### ISSUE TITLE
Crash when opening dynamic fps in mod settings

### ISSUE THREAD

**Issue by JuliadSmithe** [juliand665/Dynamic-FPS#230]
Launched the latest and a version before the latest in 1.19.2 of dynamic fps and when i try to open its configs ingame i crash 

The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalArgumentException: Root resources can only be filenames, not paths (no / allowed!)

[crash-2024-10-24_21.55.10-client.txt](https://github.com/user-attachments/files/17508030/crash-2024-10-24_21.55.10-client.txt)

**Comment by LostLuma** [comment]
Thanks for the report. I'll create an update with a fix for this in a little bit.
Sure would be nice if Forge wasn't always so annoying in the first place though ...

**Comment by LostLuma** [comment]
This is now fixed in version 3.7.5, somehow this got lost backporting since versions for 1.18.2 and below did have the fix already.

**Comment by JuliadSmithe** [comment]
Thank you so much. This mod is way too important in my modpacks.
