### ISSUE TITLE
Another crash when trying to open the config of the block swap mod

### ISSUE THREAD

**Issue by JuliadSmithe** [juliand665/Dynamic-FPS#231]
I checked out the log and it says that the suspected mod was  dynamic fps again. I updated to the latest 1.19.2 version which fixed crashing when you opened its own config but now its crashing when i open the block swap mod config and a few other mod configs

[crash-2024-10-26_11.45.35-client.txt](https://github.com/user-attachments/files/17528898/crash-2024-10-26_11.45.35-client.txt)

[crash-2024-10-26_14.19.11-client.txt](https://github.com/user-attachments/files/17529238/crash-2024-10-26_14.19.11-client.txt)

[crash-2024-10-26_16.24.50-client.txt](https://github.com/user-attachments/files/17529600/crash-2024-10-26_16.24.50-client.txt)

**Comment by LostLuma** [comment]
Hi, this is not Dynamic FPS's fault, but rather the other mods themselves.

The reason Dynamic FPS shows up in the stacktrace is that you have enabled the idle tracking feature, and it tracks whether you are actively playing the game or idling by updating a timestamp in memory whenever you use mouse or keyboard buttons (and do other actions), and you used your mouse to click on the mod list entry and/or config screen buttons.

As you can see from the stacktraces LWJGL invokes our mouse button callback (bottom two rows), and then we invoke the next mouse button callback in the chain (at the top) which eventually leads to the crash:

```java
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7] {}
	at dynamic_fps.impl.feature.state.IdleHandler.onPress(IdleHandler.java:146) ~[dynamic-fps-3.7.5+minecraft-1.19.0-forge.jar%23601!/:?] {re:mixin,re:classloading}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7] {}
```

---

I've seen lots of people misattribute this type of issue to Dynamic FPS, so I will pin this issue and hope more people see it here.
