### ISSUE TITLE
Where to find config?

### ISSUE THREAD

**Issue by XfedeX** [juliand665/Dynamic-FPS#26]
I don't know where to configure DynamicFPS in-game, but I am sure it is possible since there are the translation files for a config menu.

The only (known) way i see to configure it is manually changing file %appdata%\.minecraft\config\dynamicfps.toml .

**Comment by Felix14-v2** [comment]
You can configure it using [ModMenu](https://modrinth.com/mod/modmenu).

**Comment by juliand665** [comment]
Yeah, Mod Menu the way to get an in-game GUI. Sorry for the late reply, I thought I had already responded!

**Comment by XfedeX** [comment]
If you don't mind , I am keeping this issue open until you add this in description.

**Comment by juliand665** [comment]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/827762/123519277-732c4e80-d6aa-11eb-8bf0-8b67330533f7.png">
consider it done :)
