### ISSUE TITLE
v2.0.4 not work at all+config crash

### ISSUE THREAD

**Issue by Felix14-v2** [juliand665/Dynamic-FPS#27]
[Demo](https://youtu.be/p1UewuO1HMM)
[latest.log](https://github.com/juliand665/Dynamic-FPS/files/6716065/latest.log)
[crash-2021-06-25_15.20.23-client.txt](https://github.com/juliand665/Dynamic-FPS/files/6716066/crash-2021-06-25_15.20.23-client.txt)

The previous Cloth Config version (4.11.26) doesn't cause to crash, but Dynamic FPS still does not reduce the FPS.

**Comment by juliand665** [comment]
Hmm, it's weird that you're getting errors saying `JAVA_17`, but you are correctly using Java 16? Anyway, I did not mark 2.0.4 as supporting 1.16.5 (or anything before 1.17) on CurseForge. You can see that the most recent version for 1.16 is 2.0.2:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/827762/123426578-dee7bc00-d5c3-11eb-8996-3fbf8b980c6d.png">

**Comment by Felix14-v2** [comment]
Yes, I used Java 16 and Minecraft 1.16. But for some reason Minecraft 1.17 shows the same result. I don't have a profile for tests in 1.17 yet and I was too lazy to create it, so I checked 2.0.4 in Minecraft 1.16. Sorry for the false concern, I downloaded new version from the Github releases page, not from CurseForge.

**Comment by juliand665** [comment]
Ah, interesting. Is it possible you were using the wrong .jar? You want this one:
<img width="306" alt="Screen Shot 2021-06-26 at 18 17 06" src="https://user-images.githubusercontent.com/827762/123519335-d6b67c00-d6aa-11eb-8299-6b53b654dc43.png">

**Comment by Felix14-v2** [comment]
No, I used the correct .jar. But I deleted all config files and the problem disappeared...
I'm sorry again.
