### ISSUE TITLE
Is the mod compatible with Sodium, Lithium and Phosphor?

### ISSUE THREAD

**Issue by mscofield0** [juliand665/Dynamic-FPS#32]

**Comment by juliand665** [comment]
Yes. Why not just try it?

**Comment by mscofield0** [comment]
To be honest, you never know what might happen when you try it out. I wanted to ask in person. Might also be good to open a Discussions tab just in case more people have question so they don't open issues like this. 

Thanks for the answer

**Comment by juliand665** [comment]
In all my time making mods, every single time someone has asked about compatibility, the answer has been the same: most probably yes, just try it and see. Especially a mod like Dynamic FPS, which is purely client-side, has basically no way to break your worlds.

And when people do try it, the answer is pretty much always yes (unless it's optifine lmao), except for the very rare occurrence that someone actually does discover an incompatibility, which is then handled by opening an issue and finding a fix for the compatibility issue. In the end, only mods whose principles are irreconcilably different end up incompatible, and when that happens, you'll know just from their descriptions.
