### ISSUE TITLE
[suggestion] Menu FPS reducer

### ISSUE THREAD

**Issue by XfedeX** [juliand665/Dynamic-FPS#33]
When you have the menu (or the inventory) open, you don't see any difference between 30 and 60 FPS: in fact, lower framerate is visible especially when you move the camera.

My "benchmark": standing still at different framerates
            CPU    GPU
30fps   8%      11,5%
60fps   13%        20%

**Comment by juliand665** [comment]
I could see this making sense, but we'd have to slow down the rendering of only the world, not the GUI screens. I think it'd be annoying if e.g. dragging items had only half the FPS. What do you think?
