### ISSUE TITLE
The fishing rod can only be cast very close when using Autofish in the backend

### ISSUE THREAD

**Issue by MAX-XiaoKui** [juliand665/Dynamic-FPS#37]
I am using Autofish and Dynamic-FPS, I tried to use Autofish in the backend with Dynamic-FPS setting to 1 FPS, but the fishing rod cannot be cast far.

**Comment by juliand665** [comment]
Interesting. Does increasing the reduced FPS make it work?

**Comment by MAX-XiaoKui** [comment]
Yes, when I increases the reduced fps to 60, Autofish can normally fish.

**Comment by juliand665** [comment]
You could try lower values that are still larger than 1 and see where it starts breaking. Dynamic FPS shouldn't have any effect on game logic, but I guess Autofish is doing something weird there. Maybe you could open an issue on their tracker for this? I don't see why they should depend on how often the game is rendered.

**Comment by MAX-XiaoKui** [comment]
It starts breaking at about 15~25 fps.
The cast distance decreases as the fps decreases.
When I set fps to 10 in the frontend, it also breaks.
It seems to be Autofish's bug.

**Comment by MAX-XiaoKui** [comment]
The Autofish's dev said in MrTroot/autofish#11
> The mod simulates the equivalent of a right click

So it is Minecraft's bug?

**Comment by juliand665** [comment]
I still don't think it should depend on rendering. I'll be interested to hear what they say when you report it on their issue tracker.

**Comment by MAX-XiaoKui** [comment]
Maybe it is caused by a rendering mod I installed (maybe sodium), I'll test it later.
