### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by Madis0** [juliand665/Dynamic-FPS#4]
Could you please add a hotkey to toggle the mod's feature directly?

The GNOME desktop does not support minimizing windows and I would like to keep a key held for a farm (so no pause menu).

**Comment by juliand665** [comment]
Ooh, that sounds like a nice idea. I'd probably need to render something over the screen though, to make sure people know their fps is currently being slowed down… Or do you think that wouldn't be necessary as long as there's no key bound by default?

**Comment by Madis0** [comment]
>I'd probably need to render something over the screen though, to make sure people know their fps is currently being slowed down…

A simple overlay text would be sufficient, similar to vanilla - 

https://www.reddit.com/r/Minecraft/comments/coox20/til_you_can_actually_pause_the_game_without_pause/

**Comment by juliand665** [comment]
Right, but the text would be necessary, right? I was wondering if I could just leave it away…

**Comment by Madis0** [comment]
Yes, I would suggest using a text somewhere to keep it obvious that this is working as intended.

**Comment by juliand665** [comment]
So I finally got around to implementing this! The build will be available [on CurseForge](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps/files/2871200) as soon as they approve it, or [in the releases section](https://github.com/juliand665/Dynamic-FPS/releases/tag/1.1.0) right now :)

Another thought: doesn't it reduce to 1 FPS when unfocused already? No need to minimize, except to get that last bit of performance out.
