### ISSUE TITLE
question raised with replay mod 2.6+

### ISSUE THREAD

**Issue by SunnySlopes** [juliand665/Dynamic-FPS#40]
i've just posted an issue to replay mod for missing frames in output video, and they said

> That's the Dynamic FPS mod working as intended.
I'd recommend you open an issue on their tracker and suggest they implement grondag/frex#9. Until they do, you'll have to manually disable the mod when rendering on keep the window in focus at all times.
>
and this is the website he said: https://github.com/grondag/frex/pull/9
what's more, can you add this feature to 1.16.5 and 1.15.2 as well?
thank you!

**Comment by juliand665** [comment]
Hi! Are you still interested in this? Thanks to @altrisi's pull request (#44), Dynamic FPS should now no longer reduce FPS while rendering a video. Please give this pre-release a try and let me know if it fixes your issue :)

[dynamic-fps-2.0.6.jar.zip](https://github.com/juliand665/Dynamic-FPS/files/7358387/dynamic-fps-2.0.6.jar.zip)
