### ISSUE TITLE
[Suggestion] Suppress sound volume if the game window is inactive or minimized.

### ISSUE THREAD

**Issue by RDKRACZ** [juliand665/Dynamic-FPS#42]

**Comment by Madis0** [comment]
Maybe disabling the whole sound processing system would help with performance as well?

**Comment by juliand665** [comment]
Yeah, this would be pretty nice to have, especially if it lets us squeeze out more performance as you mentioned. I'll have to look into it sometime—I can think of a dirty way to do it (set a lower value on unfocus and restore it on focus) but I bet there's a nicer one.

**Comment by juliand665** [comment]
It's done! The new version 2.1.0 lets you set a volume multiplier when unfocused (25% by default) and when not visible (0% by default).
