### ISSUE TITLE
[Feature Request] Improve OptiFine resource pack animation compatibility

### ISSUE THREAD

**Issue by TBlazeWarriorT** [juliand665/Dynamic-FPS#43]
**Edit**: This was originally reported as a bug until I realized even optifine's own FPS cap slider causes this issue.
If this unwanted behavior is not easily avoidable on your end, you can skip this bug report and blame optifine.
One potential solution I imagine would be fully pausing animations on focus lost to avoid this, for example, but if nothing like this is possible, this is probably a lost cause.

**Environment:**
- dynamic-fps-2.0.2.jar (can start using v2.0.5 if you tell me it works in 1.16)
- fabric-api-0.37.1+1.16.jar (I dislike MC 1.17.1 but it should affect it too)
- Personal note: 1.17 is barely affected by this bug because Opti(not)Fine is (more) horrible since 1.17 and Sodium should be used, meaning no optifine RPs

**Conditions:**
- Be using an animated resource pack
- Unfocused FPS Target must be below 20 (probably because the game runs at 20 TPS)
- Lose focus and regain it

**Example of how to reproduce:**
- Download and install, for example, Fresh Animations v1.4 and Fresh Animations Addons to get a blinking villager texture
- Keep Minecraft defocused until the villager blinks
- Regain focus when the villager eyes are closed

**Consequence:**
- The animation will remain stuck at a frame for longer than it should and this can look quite bad at times
- In this example, the villager eyes will remain closed and creepy for WAY longer than they should (the screenshot only shows it when paused but it remains like that for a few seconds later)
![image](https://user-images.githubusercontent.com/25572454/134279335-9ed4af22-adef-43de-905a-9eb83622acaf.png)
This is a very minor bug, that is easy to corner and probably hard to fix, but it was happening very often to me and annoying me until I had to spend my time figuring out what on earth was going on.

**Comment by juliand665** [comment]
Thanks for the detailed writeup! Unfortunately, even if this were just an incompatibility, OptiFine is pretty impossible to support because of their closed source nature and generally weird way of doing things.

> even optifine's own FPS cap slider causes this issue
hahaha, of course it does

Just in case, have you heard of [iris](https://irisshaders.net)? Together with Sodium handling the performance side of things, you can have that and shaders, covering 90+% of OptiFine use cases.

**Comment by TBlazeWarriorT** [comment]
I started using sodium+iris when I play past 1.17, but it does not have the extra optifine resource pack features, and I believe not even the resource pack shown in this ticket would work.
There are mods being developed to readd this feature but both them and iris are incomplete.

well, if you ever find a way to fully stop animations when focus is lost, maybe something can be done (or a completely different feature), but I was already expecting it to be unfixable, I have heard before how much of a pain in the ass dealing with optifine is
