### ISSUE TITLE
[Bug] Frames aren't getting rendered properly when on idle

### ISSUE THREAD

**Issue by Blobanium** [juliand665/Dynamic-FPS#47]
So, i have come across a bug in 1.18 where it seems to be black but for a split second it shows a frame and then it goes black again... it does this every time i tab out.

Replay footage of this happening: https://streamable.com/f0xzhd

**Comment by JinxTheGoblin** [comment]
I've been getting this same thing happening to me too

**Comment by JinxTheGoblin** [comment]
might be caused by figura, but not sure

**Comment by juliand665** [comment]
Very strange! Does it still happen with just Dynamic FPS (and Fabric API)?

**Comment by JinxTheGoblin** [comment]
nope, just when figura is installed alongside

**Comment by juliand665** [comment]
fixed in figura :)
