### ISSUE TITLE
Requires Fabric API

### ISSUE THREAD

**Issue by LoganDark** [juliand665/Dynamic-FPS#51]
This mod requires Fabric API, even though it is not listed anywhere on the [Modrinth page](https://modrinth.com/mod/dynamic-fps). Until this dependency can be removed, it should be listed so that people don't get confused if their client fails to load due to it.

**Comment by juliand665** [comment]
Oops, no idea how that slipped through! I've added it to every featured version; didn't feel like going through every version I've published.
