### ISSUE TITLE
Suggestion: Delay before FPS limit kicks in

### ISSUE THREAD

**Issue by j-tai** [juliand665/Dynamic-FPS#52]
If you are switching from Minecraft to another window to check something, then switching back, it is a little jarring to see the FPS change suddenly. So it would be nice if we could configure a delay before the FPS limit kicks in. For example, the FPS could be limited after being unfocused for 30 seconds.

**Comment by juliand665** [comment]
I suppose I could see that, but on the other hand it really switches back to full FPS _instantly_ (unlike how FPS Reducer at least used to work, where it would take up to a full second to restore from 1 FPS), and it's nice to have that performance freed up right away. I guess it's a valid tradeoff to make though, I'll keep this around for discussion.

**Comment by j-tai** [comment]
Closing due to negative feedback
