### ISSUE TITLE
suggestion: turn down graphical settings in background

### ISSUE THREAD

**Issue by Meadowsys** [juliand665/Dynamic-FPS#54]
would it be viable to make minecraft render at lower settings in the background to lower use even more? (for example: turn graphics down from fabulous down to fast) I think if there is not much difference, maybe it would allow to set the FPS limit to something higher like 15, so that you can still see what is happening, just with reduced quality instead of reduced frame rates.

**Comment by juliand665** [comment]
interesting idea! i'd have to look into it, but i feel like any reasonably-impactful settings would have quite some overhead to change—render distance is the big one. i'm not sure just fabulous vs fast would make a noticeable difference in performance impact. personally i always have the mod set to 1 fps anyway; i don't generally care to see what's happening when i'm not tabbed into the game.
