### ISSUE TITLE
Black frames when sharing MC window via Discord

### ISSUE THREAD

**Issue by MADS0LADEN** [juliand665/Dynamic-FPS#57]
The screen blinks black when the frames go down to 1 FPS because im sharing the window to Discord, maybe you can fix it, maybe not ;)
(Using version 2.1)
[Video](https://youtu.be/CdwOxCt-yXw)

**Comment by MADS0LADEN** [comment]
#49 sorry for duplicate didn't search before posting

**Comment by MADS0LADEN** [comment]
I've located the issue to only appear when using optifine & optifabric

**Comment by juliand665** [comment]
Nice work tracking it down! Too bad it's OptiFine… my stance on OptiFine is that its closed-source nature makes it all-but-impossible to support, and there are [much better alternatives](https://lambdaurora.dev/optifine_alternatives/) out there for most of its features these days.

**Comment by MADS0LADEN** [comment]
Yeah its a bummer Optifine is closed down, will look into the alternatives, thanks!
