### ISSUE TITLE
High cpu usage (or game freeze) after a long time

### ISSUE THREAD

**Issue by andreasdc** [juliand665/Dynamic-FPS#59]
When you have game enabled for couple hours, you can see increased cpu usage and sometimes the game freezes when you try to unfocus.

**Comment by juliand665** [comment]
Very strange! I've never run into this. Does it happen even if Dynamic FPS (and Fabric API) is the only mod in your instance?

**Comment by andreasdc** [comment]
> Very strange! I've never run into this. Does it happen even if Dynamic FPS (and Fabric API) is the only mod in your instance?

It's very hard to tell, I can prepare spark profilers when it works normaly and when it bugs, but when it freezes it will be hard to analyze. :D You can hear sounds normally, but screen is freezed.

**Comment by juliand665** [comment]
Hm yeah, that's unfortunate. You didn't really answer my question though? If it doesn't happen when you're only using this mod and nothing else, it's probably a compatibility issue, and that would change how we need to approach it.

**Comment by andreasdc** [comment]
> Hm yeah, that's unfortunate. You didn't really answer my question though? If it doesn't happen when you're only using this mod and nothing else, it's probably a compatibility issue, and that would change how we need to approach it.

How to check it other than checking with only 2 mods?

**Comment by juliand665** [comment]
I mean, did you try checking with only those 2 mods (dynamic fps + fabric api)? Because it doesn't sound like you did, and that would be really helpful. It is pretty annoying to have to leave the game running for so long just to see if it happens again; I can't really think of a better way though…

When it freezes, is the game still running? For example, do keybinds and such still work? Also, is there maybe a way to unfreeze it?

**Comment by andreasdc** [comment]
> I mean, did you try checking with only those 2 mods (dynamic fps + fabric api)? Because it doesn't sound like you did, and that would be really helpful. It is pretty annoying to have to leave the game running for so long just to see if it happens again; I can't really think of a better way though…
> 
> When it freezes, is the game still running? For example, do keybinds and such still work? Also, is there maybe a way to unfreeze it?

Freezing happens after really long time, but I didn't have it for some time.
I have a profiler when cpu was at around 20% when minimalized, what do you want to check?

**Comment by juliand665** [comment]
Is the CPU being at 20% when minimized out of the ordinary for you? It doesn't feel like particularly high usage. As for what you should check, I honestly don't have any concrete starting points, but maybe you can try to compare it to when the usage is lower and see if anything jumps out at you?

I've been meaning to attach a profiler myself because I often get around 80% CPU usage even when not rendering at all, and I'm not really sure what's causing that.

**Comment by andreasdc** [comment]
> Is the CPU being at 20% when minimized out of the ordinary for you? It doesn't feel like particularly high usage. As for what you should check, I honestly don't have any concrete starting points, but maybe you can try to compare it to when the usage is lower and see if anything jumps out at you?
> 
> I've been meaning to attach a profiler myself because I often get around 80% CPU usage even when not rendering at all, and I'm not really sure what's causing that.
It's not ordinary, normally it's at around 4%.
Incompability with EnityCulling?
Lagged: 
![image](https://user-images.githubusercontent.com/82218780/172655164-61ddb877-40aa-41a0-ab54-9413f11c76ad.png)
Normal:
![image](https://user-images.githubusercontent.com/82218780/172655204-bec6606c-c5de-4e43-9379-f8b4d0621535.png)

**Comment by andreasdc** [comment]
@juliand665 Now I have freezed game, it's really weird. Maybe something with screen being turned off after some time?
![image](https://user-images.githubusercontent.com/82218780/172693004-38328710-8b70-4191-abcf-1f4f5db710d5.png)

**Comment by Ordinaryserver** [comment]
Ohhh...I think I'm having this issue too

**Comment by andreasdc** [comment]
Use VulkanMod instead of sodium

**Comment by Ordinaryserver** [comment]
ohhh...Im delete message.

**Comment by Ordinaryserver** [comment]
ohhh...my is delete message!

**Comment by Ordinaryserver** [comment]
ohhh.sorry! my is chinese.I have removed the comment.

**Comment by LostLuma** [comment]
@andreasdc can you still reproduce this in version 3.1.0 or later?

**Comment by andreasdc** [comment]
I didn't have this issue for a long time 🚀
