### ISSUE TITLE
Suggestion: separate slider for music volume

### ISSUE THREAD

**Issue by Slooshie1** [juliand665/Dynamic-FPS#64]
I think it would be really great if we could change the music volume while unfocused, separate from gameplay noises. For example, when I am on a server and I unfocus Minecraft to do something else, I don't want to hear Minecraft's music in the background, but I also still want to hear gameplay sounds so that I know if I am being attacked by a zombie or whatnot.

**Comment by juliand665** [comment]
Ooh, this is a great idea! Might be a bit of a pain to implement though, because instead of collectively controlling all sounds, I'd have to handle every category individually just to separate out music. If someone wants to come up with a PR or otherwise has a good idea for this, I'm all ears!
