### ISSUE TITLE
Reduce\stop game rendering when some UI pages opened

### ISSUE THREAD

**Issue by Felix14-v2** [juliand665/Dynamic-FPS#68]
## Description
Some UI pages in Minecraft has opaque background, so it makes no sence to visualise the game scene. For example, vanilla graphics settings screen, statistics screen, resource packs screen, mouse, keybinds, language, chat and other settings screens, as well as ModMenu list and mods settings.

## Why?
This idea came to me when I was playing with shaders on my old laptop. Even with minimized settings I had ≈20 fps, and it remained the same even when i opened the settings pages that completely covered the world scene.

So, I hope this setting will help other players with computers as weak as mine.

**Comment by juliand665** [comment]
This is a good idea! I'm not sure what would be the best way to detect this (hardcoding which screens it applies to is not an option) and a bit busy with other projects right now.

If someone wants to take a stab in a PR, I'm all for it!

**Comment by Felix14-v2** [comment]
This feature has been implemented, so I can happily close this. It would be great if you also supplemented the description on Modrinth, since these are quite important optimizations that people should know about :)
