### ISSUE TITLE
[1.18.2] Version question

### ISSUE THREAD

**Issue by Ullimunate** [juliand665/Dynamic-FPS#69]
Is it possible to integrate your mod into version 1.18.2 of the Fabric version soon?
I am compiling an assembly for myself, the official version 1.18.2 of your mod is sorely lacking :з

**Comment by juliand665** [comment]
I'm confused, what's the problem with the official 1.18.2 version? It should be exactly the same as what you compile yourself.

**Comment by juliand665** [comment]
Closing until further input.
