### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by Aces-and-Jacks** [juliand665/Dynamic-FPS#70]
Could you specify the mod loader that works with this on curseforge? Currently it only shows as quilt when on modrinth it says fabric also works. And on modrinth it only shows as 1.19. Asking because the launcher I use has an updater and that confuses it. 

If you don't want to do anything about it or don't know how then you can disregard this and close this issue

**Comment by juliand665** [comment]
This is actually a CurseForge issue: it handles it poorly if you support multiple loaders.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/827762/189365420-b7462862-06e2-4d91-9dde-b59a209d0747.png">
