### ISSUE TITLE
Set v2.2.0 as 1.19.1 and 1.19.2 compatible

### ISSUE THREAD

**Issue by ryanccn** [juliand665/Dynamic-FPS#71]
v2.2.0 works perfectly fine on these versions, just have to mark it as such to make modpack management and mod downloaders easier

**Comment by juliand665** [comment]
Ah, you mean on Modrinth? Looks like I forgot to update that when I updated CurseForge, whoops!

**Comment by ryanccn** [comment]
Thanks!
