### ISSUE TITLE
Delay toasts until game is focused

### ISSUE THREAD

**Issue by LostLuma** [juliand665/Dynamic-FPS#72]
Since this mod recently added the option to lower the volume while the game is not focused I thought it'd be useful to delay toast messages until the game is focused again, as the user will otherwise miss them.

While the base game only really shows toasts for gained advancements which can also be read back in chat there are some mods that show toasts with information that can not be recovered by the user, which is a bit unfortunate.

**Comment by juliand665** [comment]
This would be a cool feature! I'd have to look into it; I wonder how centralized toast handling is and how hard it would be to hook into it like that.
