### ISSUE TITLE
Abnormal use of internal server resources

### ISSUE THREAD

**Issue by Den4enko** [juliand665/Dynamic-FPS#73]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60628208/204049000-b2dc4697-e04e-4881-bf14-68d3cf003fef.png">
Is it normal? Why does this mod load the internal server so much? I am using the latest version for 1.19.2. Installed mods: DynamicFPS, FabricAPI, Spark.
https://spark.lucko.me/bFbSHzpPY8

**Comment by juliand665** [comment]
This is to be expected! You're profiling what Minecraft does while it shouldn't be doing anything, and it's indeed not really doing anything. It's just parking the thread for a while to check back later if it should keep going.
