### ISSUE TITLE
In-game FPS indicator still high when switched to background

### ISSUE THREAD

**Issue by blufish1234** [juliand665/Dynamic-FPS#76]
Although the FPS on the monitor is refreshing at 1 fps when set, the In-game FPS indicater still shows that the game renders at about 80 fps and the GPU Usage is still kind of high. 160fps when focused on window.

**Comment by blufish1234** [comment]
![image](https://user-images.githubusercontent.com/97332474/211232212-255d01d6-92ef-48d7-80ea-68748e531f6b.png)

**Comment by juliand665** [comment]
Yeah, Dynamic FPS essentially just replaces the render call with a sleep for 30ms, so it unfortunately makes the FPS counter inaccurate. However, 80 FPS should be impossible, since the method blocks for those 30ms, so the max should be around 33 FPS. Does this still happen in an instance with just Dynamic FPS?

**Comment by blufish1234** [comment]
I have disabled all of my optimising mods, but It's still 80 fps

**Comment by juliand665** [comment]
Just to be sure, could you try it in a fresh instance? I don't recall seeing this issue on Windows.

**Comment by blufish1234** [comment]
I removed all of the mods, and found out that it is for sure 30fps in singleplayer mode. On servers, however, it stays at around 50 fps

**Comment by blufish1234** [comment]
same as above when other mods are enabled again

**Comment by xpopy** [comment]
Having the same issue here, both singleplayer and multiplayer show a much higher fps than what Dynamic-FPS is set to.
The frame time graph below indicate that the mod doesn't sleep for long enough and still runs some frames at full speed.

![image](https://github.com/juliand665/Dynamic-FPS/assets/3540971/a6b4da53-f2e9-4c3d-86e9-785ebe561ac2)

**Comment by LostLuma** [comment]
As said above, this is a side-effect of checking whether the game has been re-focused again more than once a second, and cancelling the rendering of all but one frame per second if it is still not focused. I've tested only checking this once a second but then tabbing back to Minecraft feels awfully slow, whereas the current method allows resuming gameplay almost instantaneously.

The most we could do without worsening the user experience is override the frame rate in the top left of the debug screen, however I don't really see a point in this right now.

**Comment by juliand665** [comment]
Yeah, we'd have to mix into other places to manipulate the frame time statistics to match whatever it's actually rendering. It might be worth it just to reduce confusion, but I'm not sure how hard it would be.
