### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by mrjasonn** [juliand665/Dynamic-FPS#81]
Please update to Minecraft 1.19.4.

**Comment by Felix14-v2** [comment]
There is no version dependency, DynamicFPS just works fine on Minecraft 1.19.4
![image](https://user-images.githubusercontent.com/75726196/225759853-f5cd5b71-8ae6-4471-a0e2-0f42c8c12cd0.png)

**Comment by juliand665** [comment]
Was wondering if it would just work but didn't get around to trying it myself yet. I'll mark it as compatible on CurseForge/Modrinth.
