### ISSUE TITLE
Minimized window detection does not work

### ISSUE THREAD

**Issue by Leomelonseeds** [juliand665/Dynamic-FPS#84]
Hello, I've recently noticed that even while having "Volume when not visible" set to 0%, the volume does not actually reduce when I minimize the window, instead staying on the unfocused volume of 25%. After looking into it a bit more, I found a likely cause detailed in the [GLFW docs](https://www.glfw.org/docs/3.3/window_guide.html#window_hide), which seems to imply that a window being completely hidden is different to when it's minimized. 

I'm using the mod on the latest Fabulously Optimized modpack through Prism launcher on Windows with LWJGL 3.3.1, Java 17.0.1 if that's useful. Thanks for your time!

**Comment by juliand665** [comment]
Interesting! I've mostly used the mod on macOS, and that has a built-in way to hide an entire app, which my current approach detects (and iirc even minimization on macOS). It looks like I'd have to check `GLFW_ICONIFIED` to detect minimization as well, which should be pretty doable.

**Comment by Felix14-v2** [comment]
@juliand665 I noticed something even weirder: Minecraft in fullscreen mode (with borderless mining installed) after some actions with windows starts eating twice as much GPU resources, as normal game:
https://github.com/juliand665/Dynamic-FPS/assets/75726196/ab1b4578-9bda-4b9c-99bc-297f86dba58d
Maybe this is a Nvidia moment, but I tried different graphics driver versions starting from 471.68.

**Comment by juliand665** [comment]
> @juliand665 I noticed something even weirder: Minecraft in fullscreen mode (with borderless mining installed, but I don't think it's involved) after some actions with windows starts eating twice as much GPU resources, as normal game:
> 
>  2023-06-18.18-24-21.mp4 
> Maybe this is a Nvidia moment, but I tried different graphics driver versions starting from 471.68. Iirc, this is a vanilla Minecraft bug, but I couldn't find the corresponding report on the Minecraft bugtracker, maybe you know one?

I've never heard of this bug! But it is possible it's a vanilla issue; I don't see how Dynamic FPS could ever increase GPU usage.
If you can reproduce this consistently (I can't figure out a way to reproduce it just from your recording), you could try performing those same steps in vanilla and, if it doesn't happen there, with just Dynamic FPS and no other mods.

**Comment by juliand665** [comment]
Hey @Leomelonseeds, I've finally gotten around to this! Wanna check out the test build in #95?
