### ISSUE TITLE
 Performance issue

### ISSUE THREAD

**Issue by craciu25yt** [juliand665/Dynamic-FPS#87]
I'm changing some settings & mods in Fabulosly Optimized to get more performance and I'm testing the FPS, CPU and GPU usage in a void world looking at north with pitch 0 to make all of them fair and I found that disabling dynamic fps there's more instability in the fps and there's like ~1300 -1500 fps and without it ~1550 -1700 FPS

**Comment by juliand665** [comment]
So Dynamic FPS is somehow improving your FPS and making it more stable? That sounds to me like there must be some confounding factors in the tests. Especially at such high frame rates you may be turning code paths into bottlenecks that are not designed with performance in mind.

**Comment by juliand665** [comment]
Unless you mean the "Disable Dynamic FPS" keybind to disable the mod's behavior, which also could not possibly worsen performance: while disabled, the injected code to check if the next frame should be rendered is exited as early as possible, always allowing the render to go through:

https://github.com/juliand665/Dynamic-FPS/blob/d6a1ccd942735e74be567938602a62b49bcea31f/src/main/java/dynamicfps/DynamicFPSMod.java#L61
https://github.com/juliand665/Dynamic-FPS/blob/d6a1ccd942735e74be567938602a62b49bcea31f/src/main/java/dynamicfps/mixin/GameRendererMixin.java#L25

**Comment by craciu25yt** [comment]
disabling it I mean removing the mod from the mods folder

**Comment by juliand665** [comment]
And removing the mod worsens your FPS? Like I said, the only way I could see that happening was if it was helping alleviate thermal throttling.

**Comment by craciu25yt** [comment]
No. When the mod is removed there's more FPS

**Comment by juliand665** [comment]
Ahh, that makes more sense. I'll still maintain, though, that performance at such high FPS numbers really isn't meaningful.

> Especially at such high frame rates you may be turning code paths into bottlenecks that are not designed with performance in mind.

A change that doubles your fps from 60 to 120 would be incredibly unlikely to double it to 1200 if you started at 600. The game (and most mods) are simply not designed with FPS that high in mind.

**Comment by craciu25yt** [comment]
but if it has ~200 fps performance impact for me, it wouldn't in a low-end pc (for more context, I'm trying to do the most optimised modpack)

**Comment by juliand665** [comment]
If it reduces your fps from 1700 to 1500 (so by ~12%), that does not mean it would reduce someone else's fps from 60 to 53 (also ~12%), because the relevant bottlenecks might be completely different.

**Comment by craciu25yt** [comment]
oh okay, thanks

**Comment by LostLuma** [comment]
Fwiw as much as this issue was misguided, version 3.1.0 improves performance of the mod which might make you happy.
