### ISSUE TITLE
Support Minecraft 1.20 plz

### ISSUE THREAD

**Issue by AkarinLiu** [juliand665/Dynamic-FPS#90]
I am Modpacks Creator, I hope this Mod can be support Minecraft 1.20.
[My Modrinth](https://modrinth.com/user/AkarinLiu)

**Comment by LostLuma** [comment]
Hello, this has been implemented as of version [2.3.0](https://github.com/juliand665/Dynamic-FPS/releases/tag/2.3.0), also available on Modrinth and CurseForge (once approved).
