### ISSUE TITLE
Idea: Reduce FPS when inactive/no input for X amount of time (AFK)

### ISSUE THREAD

**Issue by itsTyrion** [juliand665/Dynamic-FPS#92]
How about adding a setting to also activate the cap when not making any input for, say, 2 minutes? (AFK)
This could be useful to save power, especially when playing with a fat shaderpack.

**Comment by juliand665** [comment]
I've considered something like this in the past! I wouldn't be opposed to it, but it's never been a priority since you can also just pause and tab out lol

**Comment by andreasdc** [comment]
Good idea
